version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        versions: [".*PREVIEW.*", ".*RC.*", ".*M.*"]