name: Build JVM & Push Docker image X86

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

env:
  IMAGE_NAME: agungdh/discord-bot-server-monitoring

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #########################################################
      # Build & push ketika event-nya BRANCH (bukan tag)
      #########################################################
      - name: Build & push (branch)
        if: ${{ github.ref_type == 'branch' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      #########################################################
      # Build & push khusus event TAG
      #########################################################
      - name: Build & push (tag)
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
