name: Build Native (Maven) & Upload Artifact

on:
  push:
    branches: [ master ]
    tags:     [ '*' ]
  workflow_dispatch:

permissions:
  contents: write  # perlu untuk membuat Release & upload asset

jobs:
  native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM JDK 21 (+native-image)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image (skip tests)
        run: |
          chmod +x mvnw
          ./mvnw -Pnative -DskipTests native:compile

      - name: Package artifact (zip)
        id: pack
        shell: bash
        run: |
          set -euo pipefail
          BINPATH=$(find target -maxdepth 1 -type f -perm -111 -printf "%p %s\n" \
            | sort -k2 -nr | head -n1 | awk '{print $1}')

          if [ -z "${BINPATH:-}" ] || [ ! -f "$BINPATH" ]; then
            echo "Native binary tidak ditemukan di target/." >&2
            ls -lah target || true
            exit 1
          fi

          APPNAME=$(basename "$BINPATH")

          # Tentukan suffix nama file: tag name kalau push tag, kalau bukan pakai run_id
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            SUFFIX="${GITHUB_REF_NAME}"
          else
            SUFFIX="${GITHUB_RUN_ID}"
          fi

          ZIPNAME="${APPNAME}-linux-amd64-${SUFFIX}.zip"

          echo "Jalankan: ./${APPNAME}" > target/HOW_TO_RUN.txt
          (cd target && zip -r "../${ZIPNAME}" "$APPNAME" HOW_TO_RUN.txt >/dev/null)

          # Buat checksum untuk verifikasi (ikut di-release saat tag)
          sha256sum "${ZIPNAME}" | tee "${ZIPNAME}.sha256"

          echo "zip=${ZIPNAME}"           >> "$GITHUB_OUTPUT"
          echo "checksum=${ZIPNAME}.sha256" >> "$GITHUB_OUTPUT"

      - name: Upload artifact (Actions tab)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack.outputs.zip }}
          path: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
          if-no-files-found: error
          retention-days: 14

      # Khusus kalau push tag: buat Release dan attach asset
      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
