name: Build Native (Maven) & Upload (Actions + Release)

on:
  push:
    branches: [ master ]
  release:
    types: [published]        # HANYA saat release dipublish (bukan draft)
  workflow_dispatch:

permissions:
  contents: write             # perlu untuk upload ke Releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout ke tag release kalau event release published
      - name: Checkout (release tag)
        if: github.event_name == 'release'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Checkout default untuk push ke master / manual
      - name: Checkout (branch)
        if: github.event_name != 'release'
        uses: actions/checkout@v4

      - name: Setup GraalVM JDK 21 (+native-image)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image (skip tests)
        run: |
          chmod +x mvnw
          ./mvnw -Pnative -DskipTests native:compile

      - name: Package artifact (zip)
        id: pack
        shell: bash
        run: |
          set -euo pipefail
          BINPATH=$(find target -maxdepth 1 -type f -perm -111 -printf "%p %s\n" \
            | sort -k2 -nr | head -n1 | awk '{print $1}')

          if [ -z "${BINPATH:-}" ] || [ ! -f "$BINPATH" ]; then
            echo "Native binary tidak ditemukan di target/." >&2
            ls -lah target || true
            exit 1
          fi

          APPNAME=$(basename "$BINPATH")

          # Suffix: tag untuk release published, run_id untuk push master
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            SUFFIX="${{ github.event.release.tag_name }}"
          else
            SUFFIX="${GITHUB_RUN_ID}"
          fi

          ZIPNAME="${APPNAME}-linux-amd64-${SUFFIX}.zip"

          echo "Jalankan: ./${APPNAME}" > target/HOW_TO_RUN.txt
          (cd target && zip -r "../${ZIPNAME}" "$APPNAME" HOW_TO_RUN.txt >/dev/null)

          sha256sum "${ZIPNAME}" | tee "${ZIPNAME}.sha256"

          echo "zip=${ZIPNAME}" >> "$GITHUB_OUTPUT"
          echo "checksum=${ZIPNAME}.sha256" >> "$GITHUB_OUTPUT"

      # Simpan juga di Actions artifacts (opsional tapi berguna untuk arsip CI)
      - name: Upload artifact (Actions tab)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack.outputs.zip }}
          path: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
          if-no-files-found: error
          retention-days: 14

      # HANYA saat release published: upload ke halaman Release
      - name: Upload assets to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
